#!/usr/bin/env python3
"""
Post the finding-event-judges deliverables as sections appended to the
event's planning doc.

Mirrors the pattern from finding-event-dates/scripts/post_to_doc.py: one
canonical section in the planning doc, idempotent across reruns.

The section is bracketed by a marker line so a re-run can find and delete
the prior section before appending the new one. That keeps the doc clean
instead of stacking duplicate prospect lists every time the skill runs.

Usage:
  python post_to_planning_doc.py \
    --doc-id <planning-doc-id> \
    --prospects out/prospects-ranked.md \
    --overlay out/strategic-overlay.md \
    --account aaron@aitrailblazers.org
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time

SECTION_MARKER = "Judges Research"
# Google Docs per-minute write quota is small for documents with lots of
# markdown constructs. The Judges Research section (two large tables) hits
# the quota easily. 5 retries with a 90s backoff gives 6+ full quota windows
# of headroom, which has been enough in practice for ~30-prospect runs.
MAX_RETRIES = 5
RATE_LIMIT_BACKOFF_SECONDS = 90


def gog_json(account: str, *args: str) -> dict | list:
    cmd = ["gog", "--account", account, "-j", "--results-only", *args]
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return json.loads(result.stdout) if result.stdout.strip() else {}


def gog_call(account: str, *args: str) -> str:
    last_err = ""
    for attempt in range(MAX_RETRIES):
        cmd = ["gog", "--account", account, *args]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            return result.stdout
        last_err = (result.stdout or "") + (result.stderr or "")
        if "rateLimitExceeded" in last_err and attempt < MAX_RETRIES - 1:
            print(
                f"[post_to_planning_doc] Rate-limited, waiting {RATE_LIMIT_BACKOFF_SECONDS}s "
                f"(attempt {attempt + 2}/{MAX_RETRIES})...",
                file=sys.stderr,
            )
            time.sleep(RATE_LIMIT_BACKOFF_SECONDS)
            continue
        break
    raise SystemExit(f"gog failed: {last_err.strip()}")


def find_prior_section(account: str, doc_id: str) -> tuple[int, int] | None:
    """Return (start_index, end_index) of a prior judges-research section, or None."""
    structure = gog_json(account, "docs", "structure", doc_id)
    paras = (
        structure.get("paragraphs", structure)
        if isinstance(structure, dict)
        else structure
    )
    if not isinstance(paras, list):
        return None

    marker_idx = None
    for i, p in enumerate(paras):
        text = p.get("text") or ""
        if SECTION_MARKER in text:
            marker_idx = i
            break

    if marker_idx is None:
        return None

    # Walk back through trailing blanks / rule lines so the deletion leaves
    # a clean break instead of an orphan separator.
    start_para = marker_idx
    while start_para > 0:
        prev = paras[start_para - 1]
        prev_text = (prev.get("text") or "").strip()
        if prev_text == "" or set(prev_text) <= {"-"}:
            start_para -= 1
        else:
            break

    start_idx = paras[start_para].get("startIndex")
    last = paras[-1]
    end_idx = last.get("endIndex")
    if start_idx is None or end_idx is None:
        return None
    return (start_idx, end_idx - 1)


def delete_range(account: str, doc_id: str, start: int, end: int) -> None:
    print(
        f"[post_to_planning_doc] Removing prior judges section, range {start}-{end}.",
        file=sys.stderr,
    )
    gog_call(
        account,
        "docs",
        "delete",
        "--start",
        str(start),
        "--end",
        str(end),
        doc_id,
        "-y",
    )


def build_combined_markdown(
    prospects_path: str, overlay_path: str, event_name: str | None
) -> str:
    """Combine both reports under a single top-level marker section."""
    with open(prospects_path) as f:
        prospects_md = f.read()
    with open(overlay_path) as f:
        overlay_md = f.read()

    header_lines = [
        "----------------------------------------",
        f"## {SECTION_MARKER}",
        "Generated by the finding-event-judges skill. Supersedes any prior Judges Research section above.",
        "",
    ]
    if event_name:
        header_lines.insert(2, f"Event: {event_name}")

    # Demote each report's H1 to H2 so it nests cleanly under our section
    # marker and does not compete with the planning doc's own top-level heading.
    def demote_h1(md: str) -> str:
        lines = md.splitlines()
        out = []
        for line in lines:
            if line.startswith("# ") and not line.startswith("## "):
                out.append("##" + line[1:])
            else:
                out.append(line)
        return "\n".join(out)

    parts = header_lines + [demote_h1(prospects_md), "", demote_h1(overlay_md), ""]
    return "\n".join(parts) + "\n"


def append_markdown(account: str, doc_id: str, md_path: str) -> None:
    """Append markdown to the doc, with retry-and-cleanup on partial failures."""
    cmd_args = (
        "docs",
        "write",
        doc_id,
        "--append",
        "--markdown",
        "--file",
        md_path,
    )
    last_err = ""
    for attempt in range(MAX_RETRIES):
        cmd = ["gog", "--account", account, *cmd_args]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            print(
                f"[post_to_planning_doc] Append succeeded on attempt {attempt + 1}.",
                file=sys.stderr,
            )
            print(result.stdout.strip(), file=sys.stderr)
            return
        last_err = (result.stdout or "") + (result.stderr or "")
        is_rate_limit = "rateLimitExceeded" in last_err
        print(
            f"[post_to_planning_doc] Append failed on attempt {attempt + 1}: "
            f"{'rate-limited' if is_rate_limit else 'other error'}.",
            file=sys.stderr,
        )
        if attempt == MAX_RETRIES - 1:
            break
        # Clean up any partial section landed before retry.
        partial = find_prior_section(account, doc_id)
        if partial:
            print(
                "[post_to_planning_doc] Cleaning up partial section before retry.",
                file=sys.stderr,
            )
            try:
                delete_range(account, doc_id, partial[0], partial[1])
            except SystemExit as e:
                print(f"[post_to_planning_doc] Cleanup failed: {e}", file=sys.stderr)
        if is_rate_limit:
            time.sleep(RATE_LIMIT_BACKOFF_SECONDS)
    raise SystemExit(
        f"gog append failed after {MAX_RETRIES} attempts: {last_err.strip()}"
    )


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--doc-id", required=True, help="Planning doc Google Doc ID.")
    p.add_argument(
        "--summary",
        required=True,
        help="Path to doc-summary.md (the lean section to append).",
    )
    p.add_argument(
        "--event-name",
        default=None,
        help="Optional event name shown in the section header.",
    )
    p.add_argument(
        "--account",
        default="aaron@aitrailblazers.org",
        help="Google account. Defaults to AITB.",
    )
    p.add_argument(
        "--no-replace-prior",
        action="store_true",
        help="Skip find-and-delete; just append a new section (use for audit trails).",
    )
    args = p.parse_args()

    if shutil.which("gog") is None:
        raise SystemExit("gog CLI not found on PATH. Install via Homebrew first.")

    # The summary file is small (top 5 picks + overlay summary, ~30 lines of
    # markdown). The full prospect data lives in a Google Sheet linked from
    # the summary, not in the doc itself. That keeps the doc post inside
    # one quota window so we do not need to chunk or retry through the wall
    # the way the previous full-prospects-in-doc design did.
    with open(args.summary) as f:
        summary_md = f.read()

    def _demote_h1(md: str) -> str:
        out = []
        for line in md.splitlines():
            if line.startswith("# ") and not line.startswith("## "):
                out.append("##" + line[1:])
            else:
                out.append(line)
        return "\n".join(out)

    header_lines = [
        "----------------------------------------",
        f"## {SECTION_MARKER}",
        "Generated by the finding-event-judges skill. Supersedes any prior Judges Research section above.",
        "",
    ]
    if args.event_name:
        header_lines.insert(2, f"Event: {args.event_name}")

    section_md = "\n".join(header_lines + [_demote_h1(summary_md), ""]) + "\n"

    if not args.no_replace_prior:
        prior = find_prior_section(args.account, args.doc_id)
        if prior:
            delete_range(args.account, args.doc_id, prior[0], prior[1])
        else:
            print(
                "[post_to_planning_doc] No prior judges section found. Appending fresh.",
                file=sys.stderr,
            )

    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as tmp:
        tmp.write(section_md)
        tmp_path = tmp.name
    print(
        "[post_to_planning_doc] Writing Judges Research section to planning doc...",
        file=sys.stderr,
    )
    append_markdown(args.account, args.doc_id, tmp_path)

    print(
        f"[post_to_planning_doc] Done. Doc: https://docs.google.com/document/d/{args.doc_id}/edit",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
