#!/usr/bin/env python3
"""groups.io <-> Meetup message synchronizer (orchestrator + CLI).

One daily pass:
  1. List upcoming AITB Meetup events (forward only, ACTIVE).
  2. Ensure each has a groups.io topic draft (create via Gmail draft if missing).
  3. Mirror new Meetup comments -> groups.io, and new groups.io messages ->
     Meetup, with two loop guards (text markers + synced-id ledger).
  4. Print/report everything prepared; do not create an extra email digest.

Run modes:
  --dry-run   read-only; reports what WOULD happen, writes nothing, sends
              nothing. Reads Meetup comments for every upcoming event as a
              preview even before topics exist.
  (default)   live; drafts Groups.io reply emails, posts Meetup comments, saves
              state.

Usage:
  python3 -m sync.sync --dry-run --json
  python3 -m sync.sync            # live (cron)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from typing import Any

from . import config, state
from .groupsio_adapter import GroupsioAdapter, GroupsioNotSignedIn
from .meetup_adapter import MeetupAdapter


def mirror_text(marker: str, author: str, text: str) -> str:
    author = (author or "someone").strip()
    return f"{marker} {author}: {text}".strip()


def _norm_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip().lower()


def _is_groupsio_topic_seed(event: dict[str, Any], msg: dict[str, Any]) -> bool:
    """True for the sync-created opening announcement in an event topic.

    The first groups.io message for each event is generated by this synchronizer
    when it creates the topic. That announcement should exist in email archives,
    but it is not a community reply and must not be mirrored into Meetup
    comments on the next run.
    """
    text = _norm_text(msg.get("text", ""))
    title = _norm_text(event.get("title", ""))
    event_url = _norm_text(event.get("eventUrl", ""))
    if not text or not event_url:
        return False
    if event_url not in text:
        return False
    if "replies here mirror to the meetup event comments and back" not in text:
        return False
    return not title or title in text[:500]


def _mirror(
    st: dict[str, Any],
    report: dict[str, Any],
    *,
    items: list[dict[str, Any]],
    key_fn,
    marker: str,
    source: str,
    bucket: str,
    meta: dict[str, Any],
    post_fn,
    dry_run: bool,
) -> None:
    """Mirror one direction's new items to the other platform.

    One helper for both directions so the loop guards (synced ledger + foreign
    marker) can never drift apart. Each post is independently guarded: a single
    failed post/draft is logged and skipped, never aborting the run, and state is
    persisted immediately after each successful write so a later crash cannot
    cause an already-handled item to be re-posted (duplicate) next run.
    """
    for it in items:
        key = key_fn(it["id"])
        if state.is_synced(st, key):
            continue
        if state.has_foreign_marker(it.get("text", ""), source=source):
            continue
        record = {
            **meta,
            "text": mirror_text(marker, it.get("author"), it.get("text", "")),
        }
        if dry_run:
            report["mirrored"][bucket].append(record)
            report["digest"].append(record)
            continue
        try:
            post_fn(record["text"])
        except Exception as exc:  # one bad post must not abort the run
            report["errors"].append(f"post {bucket} {key}: {exc}")
            continue
        state.mark_synced(st, key)
        state.save(st)  # durable before the next write — the write already happened
        report["mirrored"][bucket].append(record)
        report["digest"].append(record)


def run(*, dry_run: bool, max_events: int | None = None) -> dict[str, Any]:
    meetup = MeetupAdapter()
    groupsio = GroupsioAdapter()
    st = state.load()

    report: dict[str, Any] = {
        "dry_run": dry_run,
        "events": [],
        "topics": {"created": [], "existing": [], "would_create": []},
        "mirrored": {"meetup_to_groupsio": [], "groupsio_to_meetup": []},
        "directions": {"groupsio_to_meetup": "ok"},
        "digest": [],
        "errors": [],
    }

    events = meetup.upcoming_active_events()
    if max_events is not None:
        events = events[:max_events]
    report["events"] = [
        {"id": e["id"], "title": e["title"], "dateTime": e["dateTime"]} for e in events
    ]

    for ev in events:
        existing = st["event_topic_map"].get(ev["id"])
        mapping = groupsio.ensure_topic(ev, existing, dry_run=dry_run)

        if existing and mapping.get("pending"):
            try:
                found = groupsio.resolve_topic_url(mapping["topic_subject"])
                if found:
                    mapping = found
                    st["event_topic_map"][ev["id"]] = mapping
                    if not dry_run:
                        state.save(st)
            except GroupsioNotSignedIn:
                pass

        if existing:
            report["topics"]["existing"].append(ev["id"])
        elif dry_run:
            report["topics"]["would_create"].append(
                {"id": ev["id"], "subject": mapping.get("topic_subject")}
            )
        else:
            # If a topic with this subject already exists in groups.io (created
            # on a prior run / by email), resolve its URL now; else it stays
            # pending until groups.io processes the creation email.
            if mapping.get("pending"):
                try:
                    found = groupsio.resolve_topic_url(mapping["topic_subject"])
                    if found:
                        mapping = found
                except GroupsioNotSignedIn:
                    pass
            st["event_topic_map"][ev["id"]] = mapping
            # Persist immediately: ensure_topic already SENT the creation email,
            # so a crash here must not let the next run re-create (re-email) it.
            state.save(st)
            report["topics"]["created"].append(
                {"id": ev["id"], "subject": mapping.get("topic_subject")}
            )

        # --- Meetup comments -> groups.io ---
        try:
            cres = meetup.read_event_comments(ev["eventUrl"])
        except Exception as exc:  # surface, never swallow into empty
            report["errors"].append(f"read_comments {ev['id']}: {exc}")
            continue
        _mirror(
            st,
            report,
            items=cres.get("comments", []),
            key_fn=state.meetup_key,
            marker=config.MARKER_FROM_MEETUP,
            source="meetup",
            bucket="meetup_to_groupsio",
            meta={
                "event_id": ev["id"],
                "to": "groups.io",
                "subject": mapping.get("topic_subject"),
            },
            post_fn=lambda mt, mp=mapping: groupsio.post_reply(mp, mt, dry_run=False),
            dry_run=dry_run,
        )

        # --- groups.io messages -> Meetup ---
        try:
            msgs = groupsio.read_topic_messages(mapping)
        except GroupsioNotSignedIn as exc:
            report["directions"]["groupsio_to_meetup"] = f"dark: {exc}"
            msgs = []
        except Exception as exc:
            report["errors"].append(f"read_topic {ev['id']}: {exc}")
            msgs = []
        filtered_msgs = []
        for msg in msgs:
            key = state.groupsio_key(msg["id"])
            if state.is_synced(st, key):
                filtered_msgs.append(msg)
                continue
            if _is_groupsio_topic_seed(ev, msg):
                if not dry_run:
                    state.mark_synced(st, key)
                    state.save(st)
                continue
            filtered_msgs.append(msg)
        _mirror(
            st,
            report,
            items=filtered_msgs,
            key_fn=state.groupsio_key,
            marker=config.MARKER_FROM_GROUPSIO,
            source="groupsio",
            bucket="groupsio_to_meetup",
            meta={"event_id": ev["id"], "to": "meetup", "event_url": ev["eventUrl"]},
            post_fn=lambda mt, url=ev["eventUrl"]: meetup.post_event_comment(url, mt),
            dry_run=dry_run,
        )

    if not dry_run:
        state.save(st)

    return report


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="groups.io <-> Meetup synchronizer")
    ap.add_argument("--dry-run", action="store_true", help="read-only preview")
    ap.add_argument("--max-events", type=int, default=None)
    ap.add_argument("--json", action="store_true", help="emit JSON report")
    args = ap.parse_args(argv)

    report = run(dry_run=args.dry_run, max_events=args.max_events)

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        _print_human(report)
    return 0 if not report["errors"] else 1


def _print_human(r: dict[str, Any]) -> None:
    mode = "DRY RUN" if r["dry_run"] else "LIVE"
    print(f"=== AITB groups.io <-> Meetup sync ({mode}) ===")
    print(f"\nUpcoming events in scope: {len(r['events'])}")
    for e in r["events"]:
        print(f"  - {e['dateTime'][:10]}  {e['title']}  (id {e['id']})")
    tc = r["topics"]
    print(
        f"\nTopics: {len(tc['existing'])} existing, "
        f"{len(tc['created'])} created, {len(tc['would_create'])} would-create"
    )
    for t in tc["would_create"]:
        print(f"  would create: {t['subject']}")
    m2g = r["mirrored"]["meetup_to_groupsio"]
    g2m = r["mirrored"]["groupsio_to_meetup"]
    print(f"\nMirror Meetup -> groups.io: {len(m2g)}")
    for it in m2g:
        print(f"  {it['text'][:120]}")
    print(f"Mirror groups.io -> Meetup: {len(g2m)}")
    print(f"  direction status: {r['directions']['groupsio_to_meetup']}")
    if r["errors"]:
        print("\nERRORS:")
        for e in r["errors"]:
            print(f"  ! {e}")


if __name__ == "__main__":
    sys.exit(main())
