#!/usr/bin/env python3
"""Emit SQL to load the bundled research passes into the D1 cache.

    python3 scripts/seed_cache.py > seed.sql
    npx wrangler d1 execute aitb-leads --remote --file=seed.sql

The files in `public/data/` stay the source of truth and keep shipping with the site — the
cache is a second copy for cities added after a deploy, not a replacement. Seeding is
idempotent: re-running upserts rather than duplicating.

To add a city: run a research pass, write `public/data/<slug>-leads.json` in the same shape,
then either redeploy (bundled) or reseed (cached). Both paths work; bundled is faster and
survives the database being unreachable.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "public" / "data"


def sql_quote(s):
    return "'" + str(s).replace("'", "''") + "'"


def main():
    files = sorted(DATA.glob("*-leads.json"))
    if not files:
        print("-- no research passes found in public/data/", file=sys.stderr)
        return 1

    print("-- Generated by scripts/seed_cache.py — safe to re-run.")
    print("BEGIN TRANSACTION;")
    for path in files:
        doc = json.loads(path.read_text())
        slug = path.name.replace("-leads.json", "")
        leads = doc.get("leads", {})
        counts = {k: len(v) for k, v in leads.items()}
        print(f"\n-- {slug}: {counts}")
        print(
            "INSERT INTO lead_cache (city_slug, city_label, leads_json, researched_at, source)\n"
            f"VALUES ({sql_quote(slug)}, {sql_quote(doc.get('city', slug))}, "
            f"{sql_quote(json.dumps(leads, separators=(',', ':')))}, "
            f"{sql_quote(doc.get('researched_on') or doc.get('generated_for') or '')}, 'seed')\n"
            "ON CONFLICT(city_slug) DO UPDATE SET\n"
            "  city_label = excluded.city_label,\n"
            "  leads_json = excluded.leads_json,\n"
            "  researched_at = excluded.researched_at,\n"
            "  source = 'seed';"
        )
    print("\nCOMMIT;")
    print(f"\n-- {len(files)} city/cities seeded.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
